# Form implementation generated from reading ui file 'src/views/main/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("""
            QMenuBar {
                background-color: transparent;
            }
            
            QMenuBar::item {
            color : black;
            margin-top:4px;
            spacing: 3px;
            padding: 1px 10px;
            background: transparent;
            border-radius: 4px;
            }
            
            QMenuBar::item:selected {
                color: rgb(247, 247, 247);
            background: #a8a8a8;
            }
            
            QMenuBar::item:pressed {
            background: #888888;
            }
            
            QMainWindow {
                background-color: rgb(220, 226, 218);
                border: none;
            }
        """)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setContentsMargins(0, 0, 0, 0)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("""
        QWidget#centralwidget {
            background-color: rgb(220, 226, 218);
            border-top-right-radius: 10px;
            border-top-left-radius: 10px;
        }
        """)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CompMath"))

